sudo: false
language: node_js
cache: 
  directories:
    - node_modules
branches: 
  only:
    - main
notifications:
  email: false
node_js:
  - node
  - 14
before_install: 
  - npm i - g npm@latest
before_script: 
  - npm prune
after_script: 
  - npm run semantic-release